# Dependencies
# markdown:         redcarpet
markdown:         kramdown
#highlighter:      pygments
highlighter:      rouge

# Permalinks
# permalink:        pretty
#permalink:        /blog/:year/:month/:day/:title/
permalink:        /:year/:month/:day/:title/

# Setup
title:            Sound/Noise
tagline:          ''
description:      ''
url:              https://blog.pzheng.me/
paginate:         5

author:
  name:           'pzheng'
  url:            https://blog.pzheng.me/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/happybit/happybit.github.io

# support emoji
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
