# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sound/Noise
tagline:          ''
description:      ''
url:              http://blog.pzheng.info
paginate:         5

author:
  name:           'pzheng'
  url:            

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/happybit/happybit.github.io
