# Dependencies
# markdown:         redcarpet
markdown:         kramdown
highlighter:      pygments

# Permalinks
# permalink:        pretty
permalink:        /blog/:year/:month/:day/:title/

# Setup
title:            Sound/Noise
tagline:          ''
description:      ''
url:              http://blog.pzheng.info
paginate:         5

author:
  name:           'pzheng'
  url:            

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/happybit/happybit.github.io

# support emoji
gems:
  - jemoji